<Project>
  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Authors>TTS Util Win contributors</Authors>
    <Product>TTS Util Win</Product>
    <Copyright>Copyright (C) 2026</Copyright>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
